apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: custom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"                     # MongoDB Root Username
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"                 # MongoDB Root Password
        - name: MONGO_INITDB_DATABASE
          value: "mydatabase"               # Default Database Name
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db               # Mount MongoDB Data Directory
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc           # Use a Persistent Volume Claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: custom-app
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
